steps:
# Usar a ferramenta gsutil para sincronizar o repositório com o bucket
- name: 'gcr.io/cloud-builders/gsutil'
args: ['-m', 'rsync', '-r', '-c', '-d', '.', 'gs://computacao-Nuvem_API']
options:
logging: CLOUD_LOGGING_ONLY
